import { IBM_Plex_Sans_KR } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';

const inter = IBM_Plex_Sans_KR({
  subsets: ['latin-ext'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  // Add return type JSX.Element
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
